# Generated by Django 3.2.6 on 2021-11-24 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('phonenumber', models.IntegerField(validators=[users.models.validator])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/image/avatars/', verbose_name='profile picture')),
                ('avatar_thumb', models.ImageField(blank=True, null=True, upload_to='static/image/avatars/thumbs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
