# Generated by Django 3.2.6 on 2021-11-24 11:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=models.IntegerField(null=True, validators=[users.models.validator]),
        ),
    ]
