# Generated by Django 3.1.13 on 2021-08-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210810_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/avatars/thumbs/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/avatars/', verbose_name='profile picture'),
        ),
    ]
