# Generated by Django 2.2.24 on 2021-12-29 14:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211215_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='PL'),
        ),
    ]
