# Generated by Django 2.2.24 on 2022-01-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220109_0057'),
        ('users', '0004_auto_20211229_1512'),
    ]

    operations = [
    ]
