# Generated by Django 3.1.13 on 2021-09-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0002_remove_measurement_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
