# Generated by Django 3.2.6 on 2021-12-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='localization',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='with_who',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
