# Generated by Django 3.2.6 on 2021-12-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='l_lat',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='l_lon',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='localization',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='with_who',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
