# Generated by Django 3.2.6 on 2021-12-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='l_lat',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='l_lon',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=15, null=True),
        ),
    ]
