# Generated by Django 3.2.6 on 2022-01-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='cycle_interval',
            field=models.CharField(choices=[('d', 'dni'), ('w', 'tygodni'), ('m', 'miesięcy'), ('y', 'lat')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='cycle_number',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_cyclical',
            field=models.BooleanField(default=False),
        ),
    ]
