# Generated by Django 3.2.2 on 2021-06-09 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='DateTime_End',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 22, 34, 16, 740746)),
        ),
        migrations.AlterField(
            model_name='task',
            name='DateTime_Start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 9, 22, 34, 16, 740746)),
        ),
    ]
