# Generated by Django 3.2.6 on 2021-11-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_meeting_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='tasks',
        ),
    ]
