# Generated by Django 3.2.2 on 2021-06-09 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_auto_20210609_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('DateTime_Start', models.DateTimeField(default=datetime.datetime(2021, 6, 9, 22, 34, 39, 677929))),
                ('DateTime_End', models.DateTimeField(default=datetime.datetime(2021, 6, 9, 22, 34, 39, 677929))),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
