# Generated by Django 3.2.6 on 2021-12-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_auto_20211207_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='cyclical',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
