# Generated by Django 3.2.6 on 2022-01-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_auto_20220107_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='is_cyclical',
        ),
    ]
