# Generated by Django 3.2.2 on 2021-06-10 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_auto_20210609_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='DateTime_End',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 12, 5, 22, 616208)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='DateTime_Start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 12, 5, 22, 616208)),
        ),
    ]
