# Generated by Django 3.2.6 on 2022-01-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_remove_meeting_is_cyclical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='cycle_interval',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='cycle_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
