# Generated by Django 3.2.6 on 2022-01-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_auto_20220107_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='cycle_number',
            field=models.IntegerField(null=True),
        ),
    ]
