# Generated by Django 3.2.2 on 2021-06-10 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_auto_20210610_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='DateTime_End',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='DateTime_Start',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date_time_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 12, 10, 7, 194391)),
        ),
        migrations.AddField(
            model_name='meeting',
            name='date_time_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 12, 10, 7, 194391)),
        ),
    ]
