# Generated by Django 3.2.6 on 2022-01-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_alter_meeting_cycle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='cycle_interval',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='cycle_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
