# Generated by Django 3.2.2 on 2021-06-10 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_auto_20210610_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_time_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 13, 58, 17, 437178)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_time_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 10, 13, 58, 17, 437178)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
