# Generated by Django 3.2.6 on 2022-01-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_auto_20220108_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_cyclical',
            field=models.BooleanField(default=False),
        ),
    ]
