# Generated by Django 3.2.2 on 2021-06-14 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_auto_20210610_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='date_time_end',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='date_time_start',
        ),
        migrations.AddField(
            model_name='meeting',
            name='date_end',
            field=models.DateTimeField(default=datetime.date(2021, 6, 15)),
        ),
        migrations.AddField(
            model_name='meeting',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 6, 15)),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time_end',
            field=models.TimeField(default=datetime.time(0, 34, 15, 493597)),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time_start',
            field=models.TimeField(default=datetime.time(0, 34, 15, 492594)),
        ),
    ]
