# Generated by Django 3.2.2 on 2021-06-14 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0011_auto_20210615_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='date_end',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_end',
            field=models.TimeField(default=datetime.time(1, 17, 18, 755890)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_start',
            field=models.TimeField(default=datetime.time(1, 17, 18, 755890)),
        ),
    ]
