# Generated by Django 3.2.2 on 2021-06-14 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0013_auto_20210615_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date_end',
            field=models.DateField(default=datetime.date(2021, 6, 15)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_end',
            field=models.TimeField(default=datetime.time(1, 19, 25, 136899)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_start',
            field=models.TimeField(default=datetime.time(1, 19, 25, 136899)),
        ),
    ]
