# Generated by Django 3.1.7 on 2021-08-26 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0015_auto_20210825_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_end',
            field=models.DateField(default=datetime.date(2021, 8, 26)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 8, 26)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_end',
            field=models.TimeField(default=datetime.time(12, 12, 54, 202520)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_start',
            field=models.TimeField(default=datetime.time(12, 12, 54, 202520)),
        ),
    ]
