# Generated by Django 3.1.7 on 2021-06-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0016_auto_20210615_2256'),
        ('calendar_app', '0016_auto_20210615_2333'),
    ]

    operations = [
    ]
