# Generated by Django 3.1.7 on 2021-06-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0018_auto_20210616_2011'),
        ('calendar_app', '0017_merge_20210616_1914'),
    ]

    operations = [
    ]
