# Generated by Django 3.1.13 on 2021-08-28 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0026_auto_20210828_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2021, 8, 28, 20, 8, 2, 752364, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2021, 8, 28, 20, 8, 2, 752364, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_end',
            field=models.TimeField(default=datetime.time(20, 8, 2, 752364)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_start',
            field=models.TimeField(default=datetime.time(20, 8, 2, 752364)),
        ),
    ]
