# Generated by Django 3.1.13 on 2021-08-28 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0027_auto_20210828_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
