# Generated by Django 3.1.13 on 2021-08-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0028_auto_20210828_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': []},
        ),
    ]
