# Generated by Django 3.1.13 on 2021-08-28 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0029_auto_20210828_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={},
        ),
    ]
