# Generated by Django 3.2.6 on 2021-08-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0016_auto_20210826_1412'),
        ('calendar_app', '0031_auto_20210829_0043'),
    ]

    operations = [
    ]
