# Generated by Django 3.2.6 on 2021-08-29 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0032_merge_0016_auto_20210826_1412_0031_auto_20210829_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_end',
            field=models.DateField(default=datetime.date(2021, 8, 29)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 8, 29)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_end',
            field=models.TimeField(default=datetime.time(16, 5, 1, 341376)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_start',
            field=models.TimeField(default=datetime.time(16, 5, 1, 341376)),
        ),
    ]
