# Generated by Django 3.1.13 on 2021-08-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0018_auto_20210829_1333'),
        ('calendar_app', '0033_auto_20210829_1805'),
    ]

    operations = [
    ]
