# Generated by Django 3.2.6 on 2021-10-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0035_auto_20210830_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='time_start',
        ),
    ]
