# Generated by Django 3.2.6 on 2021-10-13 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0036_auto_20211013_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='time_end',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time_start',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
