# Generated by Django 3.2.6 on 2021-11-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0037_auto_20211013_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='color',
            field=models.CharField(default='blue', max_length=50),
        ),
    ]
