# Generated by Django 3.2.6 on 2021-11-21 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0038_alter_meeting_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='time_end',
            field=models.TimeField(default=datetime.datetime(2021, 11, 21, 1, 34, 13, 159514)),
        ),
    ]
