# Generated by Django 3.2.6 on 2022-01-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cyclical',
        ),
        migrations.AddField(
            model_name='task',
            name='cycle_interval',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='cycle_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_cyclical',
            field=models.BooleanField(default=False),
        ),
    ]
