# Generated by Django 3.2.6 on 2021-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211207_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ciclical',
            field=models.BooleanField(default=False),
        ),
    ]
