# Generated by Django 3.2.6 on 2021-11-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_remove_meeting_tasks'),
        ('tasks', '0002_task_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='meeting',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendar_app.meeting'),
        ),
    ]
