# Generated by Django 3.2.6 on 2022-01-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211219_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cyclical',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
