# Generated by Django 3.2.6 on 2021-11-29 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_alter_task_from_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='from_who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, validators=[tasks.models.temporary_user_validation]),
        ),
    ]
