# Generated by Django 3.1.7 on 2021-06-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
