# Generated by Django 3.1.7 on 2021-06-14 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_priority'),
        ('tasks', '0004_auto_20210614_2130'),
    ]

    operations = [
    ]
