# Generated by Django 3.1.13 on 2021-08-15 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 15), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(),
        ),
    ]
