# Generated by Django 3.2.6 on 2022-01-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20220109_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
