# Generated by Django 3.2.6 on 2022-01-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20220110_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time_interval',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
