# Generated by Django 3.2.6 on 2022-01-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20220111_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
