# Generated by Django 3.1.13 on 2021-08-27 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20210827_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.time(19, 59, 54, 173560)),
        ),
    ]
