# Generated by Django 3.2.6 on 2021-08-29 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_merge_0007_auto_20210826_1412_0022_auto_20210828_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
