# Generated by Django 3.1.13 on 2021-08-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20210829_1332'),
        ('tasks', '0024_alter_task_date'),
    ]

    operations = [
    ]
