# Generated by Django 3.2.6 on 2021-09-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_auto_20210901_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete', 'priority', 'date', 'title', 'localization']},
        ),
    ]
