# Generated by Django 2.2.24 on 2021-09-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20210914_0942'),
        ('tasks', '0028_alter_task_options'),
    ]

    operations = [
    ]
